### ISSUE TITLE
How to install for Windows?

### ISSUE THREAD

**Issue by simplesteph** [ktr0731/evans#110]
Hi

I'm planning to reference your CLI tool in my online courses for gRPC. Some of the learners are windows users and they'll need a release for windows they can download or instructions for their platform. Is your tool working for Windows? Can we please include these instructions?

Thanks a lot for the great work, been a fan for a long time! The new reflection capability is awesome

Cheers
Stephane

**Comment by ktr0731** [comment]
Hi.
Thank you for using Evans for a long time, I'm glad!
Currently, I've never tested Evans in Windows environment so Evans doesn't support it yet.

Instructions to build Evans for Windows environment is the same as normal instructions.
``` bash
$ dep ensure
$ GOOS=windows GOARCH=386 go build -o evans.exe
```

I'll plan to test Evans in Windows environment later as soon as possible.

**Comment by ktr0731** [comment]
@simplesteph 
I just merged a PR to fix Windows environment related bugs.
So, please use the latest commit (d9c7c9abf8c03999f4ef95e8e0d1c8902be2aa04) when you need to build for Windows users.
I haven't created a new GitHub Release for Windows because CI environment is not ready yet.

**Comment by simplesteph** [comment]
@ktr0731 awesome! Looking forward to the updated CI as it will make things super simple for Windows users to just download a ready-to-use exe

**Comment by simplesteph** [comment]
closing in favour of #111

**Comment by ktr0731** [comment]
Great!! 
I really pleasure that Evans is useful for your awesome gRPC course 😄

**Comment by AzharMobeen** [comment]
Evans CLI still not working for windows

**Comment by ktr0731** [comment]
Currently, Evans works fine on Windows.

**Comment by AzharMobeen** [comment]
Yes it's working fine.
