### ISSUE TITLE
Using desc on top level messages

### ISSUE THREAD

**Issue by Arg0naut** [ktr0731/evans#125]
Question re functionality of desc usage

It seems that not all messages are listed if using nested message blocks, when using the desc command

Proto snippet....

```    
    message Blog {
        string id = 1;
        string author_id = 2;
        string title = 3;
        string content = 4;
    }
```   
```  
    message CreateBlogRequest {
        Blog blog = 1;
    }
```

```
    default.BlogService@127.0.0.1:50051> show message
    +--------------------+
    |      MESSAGE       |
    +--------------------+
    | CreateBlogRequest  |
    +--------------------+
```

 ^^^ no Blog message listed above ^^^, only top level message CreateBlogRequest shown

Using desc command on CreateBlogRequest, shows it is using a field of blog of type message

```
    default.BlogService@127.0.0.1:50051> desc CreateBlogRequest
    +-------+--------------+
    | FIELD |     TYPE     |
    +-------+--------------+
    | blog  | TYPE_MESSAGE |
    +-------+--------------+
```

How then do you get a description of Blog ? I would of assumed you could do something like this....

```
    default.BlogService@127.0.0.1:50051> desc Blog
    +---------+-------------+
    |  FIELD  |    TYPE     |
    +---------+-------------+
    | id | TYPE_STRING |
    +---------+-------------+
    | author_id | TYPE_STRING |
    +---------+-------------+
    | title | TYPE_STRING |
    +---------+-------------+
    | content | TYPE_STRING |
    +---------+-------------+
```

Digging into the code -> https://github.com/ktr0731/evans/blob/master/adapter/protobuf/message_builder.go

I interpret the comment at line 15 of the above link as being able to handle these nested message blocks and being able to decode nested message blocks into there fields as my example of 'desc blog' above

On a separate note, There also seems to be some bug with auto suggestion see below image

![screenshot from 2018-11-06 09-37-32](https://user-images.githubusercontent.com/1790846/48055670-0df95700-e1a8-11e8-888f-7fbb2ba8271d.png)

Thanks in advance

**Comment by simplesteph** [comment]
FYI @ktr0731 , this is coming from a student from my course. The project is here https://github.com/simplesteph/grpc-go-course/tree/master/blog. To reproduce, just run mongodb in the backend `docker run -p 27017:27017 mongo:4`, install the mongodb driver: `go get github.com/mongodb/mongo-go-driver/mongo` and you should be good to do `go run blog/blog_server/server.go`, which has reflection enabled: `evans -p 50051 -r`

**Comment by ktr0731** [comment]
Thank you for submitting an issue!
It seems like it is a gRPC reflection related bug because Evans without gRPC reflection shows `Blog` message normally.

<img width="349" alt="2018-11-06 19 47 43" src="https://user-images.githubusercontent.com/12953836/48059559-dbc61480-e1fc-11e8-8fe9-57734423d71b.png">

Also I'll try to fix it tomorrow.

**Comment by Arg0naut** [comment]
Wow - quick response - Thanks ktr0731!

**Comment by Arg0naut** [comment]
Confirmed - Thanks for quick fix ktr0731!

![evans-0 6 8](https://user-images.githubusercontent.com/1790846/48117264-8cb1cb00-e260-11e8-895c-6cff678b16d6.png)
