### ISSUE TITLE
Pressing enter without entering a value should assume the type default 

### ISSUE THREAD

**Issue by simplesteph** [ktr0731/evans#137]
I have a Boolean field for example, or int, and if I press enter without entering a value I get an error. In gRPC it's fine not to enter values for fields as they'll be assumed by protocol buffers to be default, so it'd be good for our personal efficiency to have the same behaviour with Evans

**Comment by simplesteph** [comment]
Great ! Please note it's slightly different. Enter enter doesn't work for Boolean or int. Only string. He's asking for shift enter

**Comment by ktr0731** [comment]
Oh, I misread a little. Thanks for the complement!

**Comment by simplesteph** [comment]
@ktr0731  maybe we should re-open this as they're different?

**Comment by ktr0731** [comment]
Yes, we should it.

**Comment by simplesteph** [comment]
@ktr0731 opened https://github.com/ktr0731/evans/pull/138 :)
