### ISSUE TITLE
Not able to download file from URL :https://github.com/ktr0731/evans/releases/download/0.6.10/evans_darwin_amd64.tar.gz

### ISSUE THREAD

**Issue by SunilTiwari28071987** [ktr0731/evans#140]
Hi I am trying to install Evans on Mac for the latest release but it is giving the following error.

$ brew install evans
==> Installing evans from ktr0731/evans
==> Downloading https://github.com/ktr0731/evans/releases/download/0.6.10/evans_darwin_amd64.t

curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "evans"
Download failed: https://github.com/ktr0731/evans/releases/download/0.6.10/evans_darwin_amd64.tar.gz

**Comment by ktr0731** [comment]
Thanks for submitting an issue. I've fixed a broken release v0.6.10. Please try to install again.
