### ISSUE TITLE
[Feature Request] Sending request with metadata

### ISSUE THREAD

**Issue by soichisumi** [ktr0731/evans#148]
Is there any plan to support sending a request with metadata? 
I want to pass [metadata](https://grpc.io/docs/guides/concepts.html#metadata) to my grpc services.

The feature is necessary to test/debug grpc services with authentication.

**Comment by ktr0731** [comment]
Hi.
Evans supports gRPC metadata as `header` commands (in the case of REPL mode) or `--header` flags (in the case of CLI mode).
Please see each help message for more details.

**Comment by maxsommer** [comment]
@ktr0731 Is response metadata also supported? If so, how can I display it? If there's something available how can we help document it? 😊

**Comment by whypro** [comment]
@ktr0731 How can I pass the k, v which contain spaces or other special characters to cli?
I try to pass flags below:
```
--header token="abc xDURW=adXMf+"
```
But it says:
```
evans: invalid argument "token=abc xDURW=adXMf+" for "--header" flag: token=abc xDURW=adXMf+ must be formatted as key=value
```

**Comment by ktr0731** [comment]
@maxsommer 
I'm sorry, I was overlooked your question...
Such a feature is not implemented yet, but it seems to several users want it. So, we'll implement it in the near feature.

**Comment by ktr0731** [comment]
@whypro 
It is a bug. So, I created https://github.com/ktr0731/evans/issues/211 for fixing the bug.
