### ISSUE TITLE
rpc error: code = Unimplemented desc = Method not found!

### ISSUE THREAD

**Issue by somerska** [ktr0731/evans#157]
call doesn't work on any rpc request.  Windows 64-bit using evans_windows_amd64.exe.tar.gz

127.0.0.1:50051> package api

api@127.0.0.1:50051> service SynchronousHandler

api.SynchronousHandler@127.0.0.1:50051> call UnaryCall
age (TYPE_INT32) => 30
rpc error: code = Unimplemented desc = Method not found!

api.SynchronousHandler@127.0.0.1:50051>

I've tried this on various unary calls and none of them work. 

syntax = "proto3";

package api;

service SynchronousHandler {
  
  rpc UnaryCall(UnaryReq) returns (empty) {}

}

message UnaryReq {
    int32 age = 1;
}

message empty {
}

**Comment by ktr0731** [comment]
These are not Evans's bugs. Probably, your gRPC server implementation returns an unimplemented error which is defined in gRPC.

**Comment by somerska** [comment]
My server works fine with my client, here's all of the server code,

`from concurrent import futures
import time
import grpc
import test_pb2_grpc
import test_pb2

ONE_DAY_IN_SECONDS = 60 * 60 * 24

class SynchronousHandler(test_pb2_grpc.SynchronousHandlerServicer):
    def UnaryCall(self, request, context):
        return test_pb2.empty()

def serve():
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    test_pb2_grpc.add_SynchronousHandlerServicer_to_server(SynchronousHandler(), server)
    server.add_insecure_port('[::]:50051')
    server.start()
    try:
        while True:
            time.sleep(ONE_DAY_IN_SECONDS)
    except KeyboardInterrupt:
        server.stop(0)


if __name__ == '__main__':
    serve()`

**Comment by ktr0731** [comment]
The error says "Method not found!". Your gRPC server or a something is returning it because Evans never return such a message.
If you can give me a Dockerfile including the gRPC server, I can test it.

**Comment by acmujica** [comment]
Small issue and may be unrelated but according to the style guide ( https://developers.google.com/protocol-buffers/docs/style ) the message type in your protobuf file should start with a capital.  so message Empty {} and test_pb2.Empty() in your file.

**Comment by somerska** [comment]
I think there might be a proxy issue.  I don't understand it though because my server and client communicate fine.  Is there an option to set the proxy in Evans?

**Comment by ktr0731** [comment]
I've never test proxies for gRPC servers.
Could tell me more decription about your proxy?
