### ISSUE TITLE
Filed to use straming in CLI modle 

### ISSUE THREAD

**Issue by jankeyfu** [ktr0731/evans#166]
hi, when I use Evans's CLI model to call a rpc with server stream, then the error occurred 

failed to create client stream: failed to create server stream: failed to instantiate gRPC stream: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: <nil>

is there anything wrong?

![image](https://user-images.githubusercontent.com/19988523/53940787-868a0900-40f1-11e9-90ae-7c962a6d9c0a.png)

**Comment by ktr0731** [comment]
Is your server running with TLS? If it is, you need to launch Evans with `--tls` option.
Please show me more details about your server if it isn't running with TLS.
