### ISSUE TITLE
Using TLS mode with CACert auth error

### ISSUE THREAD

**Issue by abhilash93** [ktr0731/evans#170]
rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: cannot validate certificate for xx.xx.xx.xx because it doesn't contain any IP SANs"

I am getting the following error while calling a service on the gRPC server with TLS in CLI mode. 
Is there any way we can provide custom Common Name for the connection  xx.domain.com?

Any other suggestion for this error?

**Comment by ktr0731** [comment]
Evans provides the `--host` flag. Have you tried to use it?

**Comment by abhilash93** [comment]
echo '{"user_name": "xxxx", "password" : "xxxxx", "client_id" : "xxxxx"}' | evans --cli --verbose --service Login --call LoginCheck -t --verbose --cacert /home/xxxx/WRootCA.crt --host xx.xx.xx.xx --port xxxx

Yes I have used it but looks like the server accepts Common Name(CN) in some other format.

**Comment by ktr0731** [comment]
I see. Currently, Evans doesn't have a feature what override the common name of the gRPC server.
However, it seems to easy to implement such a feature, so I'll try to do it later.

**Comment by abhilash93** [comment]
Thank you for the update.

**Comment by abhilash93** [comment]
Can we make two rpc call in CLI mode one after other.. in the back end will it use the same connection?

I have 2 services
1) authentication 
2) serverStream

Both should happen in same netty coonection

**Comment by ktr0731** [comment]
No, it can't. CLI mode can't send two or more requests itself, so you need to prepare a shell script to achieve it.

**Comment by ktr0731** [comment]
I implemented this feature in #171.

**Comment by abhilash93** [comment]
Thank you for the quick update it worked !!

**Comment by abhilash93** [comment]
package.service@xx.xx.xx.xx:XXXX> call rpcXXX
<repeated> input::collector_list::address (TYPE_STRING) =>
<repeated> input::collector_list::address (TYPE_STRING) =>
<repeated> path_list::path (TYPE_STRING) => /path/path/state/
<repeated> path_list::filter (TYPE_STRING) => ""
<repeated> path_list::suppress_unchanged (TYPE_BOOL) => false
<repeated> path_list::max_silent_interval (TYPE_UINT32) => 50000
<repeated> path_list::sample_frequency (TYPE_UINT32) => 0
<repeated> path_list::need_eom (TYPE_BOOL) => false
<repeated> path_list::origin (TYPE_STRING) => ""
<repeated> path_list::target_defined (TYPE_BOOL) => false
<repeated> path_list::path (TYPE_STRING) => /path/path/xxx/
<repeated> path_list::filter (TYPE_STRING) => ""
<repeated> path_list::suppress_unchanged (TYPE_BOOL) => false
<repeated> path_list::max_silent_interval (TYPE_UINT32) => 10000
<repeated> path_list::sample_frequency (TYPE_UINT32) => 0
<repeated> path_list::need_eom (TYPE_BOOL) => false
<repeated> path_list::origin (TYPE_STRING) => ""
<repeated> path_list::target_defined (TYPE_BOOL) => false

how can we give empty value to the String with out breaking the repeated loop?
If I just press ENTER its breaking the repeated loop of an object(Path: that has multiple attributes). I have given ""
Please suggest

**Comment by ktr0731** [comment]
In this short term, there are no ways to input empty values for repeated messages. In the nearly future, we remove the feature what break the repeated field loop by entering <kbd>Enter</kbd> two times. After that, you will be able to input empty values by just entering <kbd>Enter</kbd> just like normal fields' one.

**Comment by ktr0731** [comment]
If you have other questions that don't relate to this issue, please submit another issue again.
