### ISSUE TITLE
[feature request] arrow up / down keys to cycle through previous commands

### ISSUE THREAD

**Issue by eddex** [ktr0731/evans#191]
**Feature description:**
Use the arrow up / down keys to cycle through previous commands.

As a user I often have to use the same calls. It would be nice to have a simple way to access and run previous commands.

This somewhat works already but when I use a command with autocomplete like `call hello <TAB> <ENTER>` to execute `call helloRequest` and then press the arrow up key, instead of  `call helloRequest` only `call hello` appears.

**Comment by eddex** [comment]
It actually seems to work sometimes. Maybe this is an issue with Powershell and the [microsoft terminal](https://github.com/Microsoft/Terminal) that I'm using.

**Comment by tuscland** [comment]
Additionally, it would be great to be able to repeat the last request issued.

**Comment by Artanicus** [comment]
On Ubuntu the feature is there but the results seem non-deterministic. i.e. it goes back in history, but not to the one I just ran but to the one I ran yesterday. Either it's trying to be too smart or it's broken.
