### ISSUE TITLE
reflection mode `evans -r` doesn't work

### ISSUE THREAD

**Issue by hiromaily** [ktr0731/evans#199]
Though I implemented reflection in server code, command `evans -r` emits errors 
```
$ evans -r
evans: failed to run REPL mode: failed to instantiate a new spec: failed to instantiate the spec from proto files: Service not found: xxxx.XXXService
```

Of course I added reflection in server code before runing `s.Serve(lis)`
```
reflection.Register(s)
```

However it works with proto path
```
evans protobuf/proto/xxx/xxx.proto
```

Is there something precondition to run evans as reflection mode?

go version is
```
go version go1.13.1 darwin/amd64
```

**Comment by ktr0731** [comment]
Can you **call** RPCs without gRPC reflection? 
gRPC reflection will be enabled by the instruction you did (at least it works fine in my environment).

If you can call RPCs without gRPC reflection, please submit a Docker image that reproduces the problem.

**Comment by hiromaily** [comment]
@ktr0731 Thanks. I'll try rpc later.
BTW, I use this code
https://github.com/hiromaily/golibs/blob/master/grpc/server/main.go
https://github.com/hiromaily/golibs/blob/master/protobuf/proto/sample/sample.proto

**Comment by ktr0731** [comment]
I think your protoc or Go proto plugin is too old because it works after re-generate pb.go with version 3.6.1 and 3.10.0.
