### ISSUE TITLE
Issue parsing JSON header value

### ISSUE THREAD

**Issue by DRayX** [ktr0731/evans#218]
I have a header value that looks something like `{"foo": "bar", "baz": "qux"}`.  In repl mode, if one simply attempts `header example={"foo": "bar", "baz": "qux"}` you end up with the value `{foo:`.  Adding single quotes gets closer, with `header example='{"foo": "bar", "baz": "qux"}'` the example header ends up with two values `{"foo": "bar"` and ` "baz": "qux"}`.  I can't find any way to actually set a header to a value containing commas.  It seems like being able to set a header to a JSON value should be possible.

**Comment by ktr0731** [comment]
The command-line option `--header` is able to accept multiple headers by comma-separated style. So, if we want to set multiple headers in one action, use it with some command-line tools. 
For example:
``` bash
$ headers=$(echo '{"foo": "bar", "baz": "qux"}' | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' | xargs echo | tr ' ' ',')
$ evans -r --header $headers
```

**Comment by DRayX** [comment]
Sorry, I don't think I was very clear; I'm trying to have a single header where the (single) value is a JSON string (which is actually a JSON formatted protobuf).

**Comment by ktr0731** [comment]
Oh, I'm sorry, I misunderstood. And thanks for additional information.
It may be a bug related to the header parser, so I'll investigate it later.

**Comment by DRayX** [comment]
Looking through repl/command.go, it uses "," as a value separator. With this design, it is impossible to have a value that contains commas.  Since it is already possible to set multiple header values just by specifying the header multiple times (e.g. `foo=bar foo=baz`), it may be better to just drop the comma separated values thing entirely.

Note that this is even more complicated with the CLI flag since app/flag.go does a first pass with a csv.Reader, which will complicate handling of quotes and commas further.

**Comment by ktr0731** [comment]
Yes, as you said, this design cannot parse a value that contains a comma. So, it is better to drop the comma-separated values thing, but I think it shouldn't for backward-compatibility.
For that reason, I'm planning to drop the feature in the major release (v1.0.0) and keep it until then.

Instead of dropping the feature, I'm thinking to add an option flag for `header` command that disables comma interpretation (and it will be dropped in v1.0.0).
