### ISSUE TITLE
Question: How do I enter repeated strings ?

### ISSUE THREAD

**Issue by karlmutch** [ktr0731/evans#22]
When using the interactive prompts how do I enter repeated strings into a single field at the prompt ?

**Comment by ktr0731** [comment]
i'm sorry, currently inputting logic related to repeated fields is broken...
however, i fixed it in branch [fix-repeated](https://github.com/ktr0731/evans/tree/fix-repeated).
i still need to write some tests and merge it to master, it takes just a moment.
if you have to input repeated fields ASAP, please use this branch.

**Comment by ktr0731** [comment]
it is merged to master branch.
you can input repeated fields and it can be finished by entering blank line at two times.
