### ISSUE TITLE
can't desc enum type: 

### ISSUE THREAD

**Issue by avamingli** [ktr0731/evans#253]
## Describe the bug
as the title, when desc an enum type:

**command desc: failed to get the type descriptor: failed to get the type descriptor of 'Codes': no such type 'api.Codes'**

proto file:

```
syntax = "proto3";

package api;

enum Codes {
  UNSPECIFIED = 0;
  STOPPED = 1;
  RUNNING = 2;
  STOPPING = 3;
  ERROR = 4;
}

message JobStatus {
  Codes code = 1;
  string msg = 2;
}

// services
```

## To reproduce
just define an enum type and desc it

## Expected behavior
desc the enum type

## Environment
- OS: macOS Mojave 10.14.5
- Terminal:  iTerm2
- Evans version: 0.8.5
- `protoc` version: libprotoc 3.7.1
- `protoc` plugin version (if you are using):

## Additional context
I search the error message from branch master, and found the error should come from 
`usecase/get_type_descriptor.go` line 20:
```
	d, err := m.spec.ResolveSymbol(fqmn)
	if err != nil {
		return nil, errors.Wrapf(err, "failed to get the type descriptor of '%s'", typeName)
	}
```
and the only implementation of `spec` is
`idl/proto/proto.go`
```
// ResolveSymbol returns the descriptor of the passed fully-qualified descriptor name.
// The actual type of the returned interface{} implements desc.Descriptor.
func (s *spec) ResolveSymbol(symbol string) (interface{}, error) {
	for _, f := range s.fileDescs {
		d := f.FindSymbol(symbol)
		if d != nil {
			return d, nil
		}
	}
	return nil, idl.ErrUnknownSymbol
}
```
but if there was an error, it should be `ErrUnknownSymbol`(**"unknown symbol"**) and  do not contain the message **"no such type"**
so , I lost 

I install from `brew`, maybe it's a reason why I can't find the error message `no such type` from master branch

**Comment by ktr0731** [comment]
Currently, `desc` command is for message types, so Evans cannot describe enum types.
In the near future, we are considering support enum types.
