### ISSUE TITLE
Unsupported codec error when using google.protobuf.Timestamp

### ISSUE THREAD

**Issue by neimus** [ktr0731/evans#265]
## Describe the bug
Error calling rpc method in cli mode:
`echo '{"2022-04-15T12:30:15.01Z"}' | evans cli --call GetTestList`

> evans: failed to run CLI mode: failed to call RPC 'GetTestList': unsupported codec

If the `google.protobuf.Timestamp` parameter is passed in the method:
`
Test {
    rpc GetTestList (google.protobuf.Timestamp) returns (TestList) {}
}
`

## Expected behavior
The request is sent successfully as in REPL mode

## Environment
- OS: MacOs
- Terminal: iTerm2
- Evans version: 0.8.5
- `protoc` version: 3.11.4

**Comment by ktr0731** [comment]
`'{"2022-04-15T12:30:15.01Z"}'` is not a valid JSON string.
The error message is not appropriate...
