### ISSUE TITLE
Show error code/message on failed rpc

### ISSUE THREAD

**Issue by robsonmeemo** [ktr0731/evans#272]
## To reproduce
```
schema.rpc.Fern@localhost:9999> call --enrich GetUser
command call: inputting canceled
```

## Expected behavior
Show the error code

## Environment
- OS: mac
- Terminal: iterm2
- Evans version: 8ecfcc82bc18fafc34b94a3854504fa322511430

**Comment by ktr0731** [comment]
I didn't reproduce in local environment. Please describe more information.

**Comment by robsonmeemo** [comment]
I'm using grpc-web.

**Comment by jrusso1020** [comment]
We've have also started to observe this on `evans 0.10.0` 

I have noticed it only happens on our grpc services that do not have reflection enabled

**Comment by raboof** [comment]
I'm also seeing this when doing a grpc-web request (which looking at wireshark *seems* to be successful, but I'm not 100% confident on that):

```
com.example.protos.Hello@127.0.0.1:8081> call SayHello
name (TYPE_STRING) => asdf
command call: inputting canceled
```

![grpc-web](https://user-images.githubusercontent.com/131856/140953449-160e8e37-b2b9-41e2-a376-0ed2fa79bb99.png)

**Comment by jrusso1020** [comment]
I figured out our issue. 

We actually are wrapping evans in our own custom CLI and we weren't setting stdin correctly to the same stdin used by our CLI
