### ISSUE TITLE
How correctly run evans (gRPC client)?

### ISSUE THREAD

**Issue by nurzhannogerbek** [ktr0731/evans#288]
I have a `city.proto` file where I import a well-known third-party package called [gogoproto](https://github.com/gogo/protobuf). I created gRPC server and now I want to test it's rpc methods by `evans` gRPC client.

I used such **command** but it raise an error:
`evans proto/city.proto --host localhost --port 8000`

**Error**:

> evans: failed to run REPL mode: failed to instantiate a new spec: failed to instantiate the spec from proto files: proto: failed to parse passed proto files: proto/city.proto:7:8: open github.com/gogo/p
> rotobuf/gogoproto/gogo.proto: The system cannot find the path specified.

**city.proto**:
```
syntax = "proto3";

package proto;

import "google/protobuf/wrappers.proto";
import "google/protobuf/timestamp.proto";
import "github.com/gogo/protobuf/gogoproto/gogo.proto";

option go_package = "./proto";

message City {
    uint64 id = 1 [
        json_name = "id",
        (gogoproto.jsontag) = "id"
    ];
    google.protobuf.Timestamp foundation_date = 2 [
        json_name = "foundation_date",
        (gogoproto.jsontag) = "foundation_date",
        (gogoproto.nullable) = false,
        (gogoproto.stdtime) = true
    ];
    google.protobuf.StringValue name = 3 [
        json_name = "name",
        (gogoproto.jsontag) = "name",
        (gogoproto.wktpointer) = true
    ];
    google.protobuf.StringValue country = 4 [
        json_name = "country",
        (gogoproto.jsontag) = "country",
        (gogoproto.wktpointer) = true
    ];
}

***
```

_go version_:
`go version go1.12.9 windows/amd64`

_protoc version_:
`libprotoc 3.11.4`

_evans version_:
`0.9.0`

In all probability, I am not correctly trying to start REPL mode. I assume that the command needs to specify the path to the directory where third-party proto files are located. I am confused. How start evans (gRPC client) correctly?

**Comment by ktr0731** [comment]
To run Evans correctly, it's required to specify the correct paths to search for imports by using `--path`.
It is almost similar to `--proto_path` in `protoc`.  
For example, we assume that `github.com/gogo/protobuf` is located in `/path/to/github.com/gogo/protobuf`:

``` go
$ evans --path /path/to --path . proto/city.proto
$ evans --path /path/to --path . --proto proto/city.proto # Better
```

Note that `--path .` is also required to search `proto/city.proto`.

Well-known protos managed by Google such as `google/protobuf/wrappers.proto` and `google/protobuf/timestamp.proto` are loaded by default, but in other cases, we have to specify correct paths to use third-party protos.

**Comment by nurzhannogerbek** [comment]
@ktr0731 thank you very much for your detailed answer!

**Comment by zxyang625** [comment]
@ktr0731 
Excuse me, I am a new beginner about evans and I have some problems on how to use it on Windows.

I run a server on localhost:8080 and have enabled gRPC reflection. So I want to start evans to test my own protos. 
I have tried to use a few commands like:

> $evans repl -r  -p 8080
> $evans --path ./ --proto proto/test.proto -p 8080

After typing `show package` and `show service`, all I have are below:

> 127.0.0.1:8080> show package
+---------+
| PACKAGE |
+---------+
+---------+

> 127.0.0.1:8080> show service
+---------+-----+--------------+---------------+
| SERVICE | RPC | REQUEST TYPE | RESPONSE TYPE |
+---------+-----+--------------+---------------+
+---------+-----+--------------+---------------+


go version:
> go version go1.16.3 windows/amd64

protoc version
> libprotoc 3.17.0

evans version
> evans 0.9.3

I guess it might have something wrong with command or my server.  I' d appreciate it if you could help solve my confusion. You can suppose that my protos are located in E:/gRPCPro/src/proto. Thanks a lot!

**Comment by bvsvntv** [comment]
> [@ktr0731](https://github.com/ktr0731) Excuse me, I am a new beginner about evans and I have some problems on how to use it on Windows.
> 
> I run a server on localhost:8080 and have enabled gRPC reflection. So I want to start evans to test my own protos. I have tried to use a few commands like:
> 
> > $evans repl -r  -p 8080
> > $evans --path ./ --proto proto/test.proto -p 8080
> 
> After typing `show package` and `show service`, all I have are below:
> 
> > 127.0.0.1:8080> show package
> > +---------+
> > | PACKAGE |
> > +---------+
> > +---------+
> 
> > 127.0.0.1:8080> show service
> > +---------+-----+--------------+---------------+
> > | SERVICE | RPC | REQUEST TYPE | RESPONSE TYPE |
> > +---------+-----+--------------+---------------+
> > +---------+-----+--------------+---------------+
> 
> go version:
> 
> > go version go1.16.3 windows/amd64
> 
> protoc version
> 
> > libprotoc 3.17.0
> 
> evans version
> 
> > evans 0.9.3
> 
> I guess it might have something wrong with command or my server. I' d appreciate it if you could help solve my confusion. You can suppose that my protos are located in E:/gRPCPro/src/proto. Thanks a lot!

did you figured it out ?
