### ISSUE TITLE
Support for flatbuffers

### ISSUE THREAD

**Issue by jaeyeonling** [ktr0731/evans#297]
It is possible to use flatbuffers?
There is support for golang in Flatbuffers as described in https://google.github.io/flatbuffers/flatbuffers_support.html

**Comment by ktr0731** [comment]
As described in README.md, currently Evans only supports Protocol Buffers3.
We'll consider it if there are a lot of requests and using gRPC + Flatbuffers to be more popular, but we aren't considering it at the moment.
