### ISSUE TITLE
Use OptionLivePrefix added from go-prompt v0.2.0

### ISSUE THREAD

**Issue by c-bata** [ktr0731/evans#30]
Hi @ktr0731!
First, I want to say congrats that evans reached 100 stars. I was sure that this will be popular.

Yesterday I released go-prompt v0.2.0 which includes a feature to change prefix string dynamically. I hope evans use this and it's implementation is more simple.

* CHANGELOG: https://github.com/c-bata/go-prompt/blob/master/CHANGELOG.md
* Example of OptionLivePrefix: https://github.com/c-bata/go-prompt/blob/master/_example/live-prefix/main.go

Thanks.

**Comment by ktr0731** [comment]
hi @c-bata.
thank you so much, I'm glad to accept Evans which is built with your cool library, go-prompt by a lot of GitHub users 😄   

> Yesterday I released go-prompt v0.2.0 which includes a feature to change prefix string dynamically. 

it's a great feature! I will improve the implementation as soon as possible.

thanks.

**Comment by ktr0731** [comment]
updated in #31
