### ISSUE TITLE
no security token is provided 

### ISSUE THREAD

**Issue by mrturkmencom** [ktr0731/evans#302]
I am using latest version of evans and would like to test my brand new gRPC calls through evans. However the problem is occuring when I try to connnect to gRPC server, since I have user based authentication system, evans throws following error: 

**" failed to instantiate the spec from proto files: failed to list packages by gRPC reflection: failed to list services from reflecton enabled gRPC server: rpc error: code = Unknown desc = No security token provided"** 

I know what does it mean, when I do not login with any credentials to gRPC server, it is normal to see "No security token provided". 

My question is that is not a way that I can provide username and password when I use evans ? 

Like : 

```bash 
$ evans -r -p 9000 --username admin --password something
```

or in any other format that I can provide user credentials.  I have checked docs and could not see anything related to it.

**Comment by ktr0731** [comment]
I don't know about your authentication system, but if it authenticates users by using header metadata (for example, `Authorization: bearer <token>`), we can use `--header` flag to specify security token.  
However, it is the case of method invocation other than gRPC reflection. So, we might have to introduce a new feature that can specify headers in gRPC reflection requests.

If your authentication system doesn't use header metadata, could you tell me about authentication flow?

**Comment by mrturkmencom** [comment]
Thank you very much for your reply. I am using header metadata for authenticating users however token is auto generated from daemon side (which means I am not outputting the token), users should provide username and password. The rest is left to gRPC server side, for this reason, I am unable to use evans such a situation, I have tried following; 

```bash 
$ evans -r -p 9000 --header username=something password=something
```
however received same error as before. Do not you think, it is possible to include username and password parameter rather than token for simplicity.

**Comment by ktr0731** [comment]
There are no protocols for authentication in gRPC. So, we don't want to add a feature related to authentication.
Also, if we assume that we introduce `--username` and `--password` flags, Evans doesn't know what protocol we should use for authentication.

Could you generate a security token via a command-line tool or others? It's the best way.

**Comment by mrturkmencom** [comment]
Sorry for late response. I think, the issue can be closed. Thanks for your response @ktr0731

**Comment by cihati** [comment]
> However, it is the case of method invocation other than gRPC reflection. So, we might have to introduce a new feature that can specify headers in gRPC reflection requests.

@ktr0731 I'm having this exact issue, help is appreciated 🙏

**Comment by ktr0731** [comment]
Hi, @cihati. Could you create a new issue for the new feature?
