### ISSUE TITLE
cannot use error in go get

### ISSUE THREAD

**Issue by emadghaffari** [ktr0731/evans#316]
## Describe the bug
when i try to use go get github.com/ktr0731/evans

output is:
ktr0731/go-prompt/internal/term/raw.go:25:75: cannot use (*syscall.Termios)(&n) (type *syscall.Termios) as type *unix.Termios in argument to termios.Tcsetattr
ktr0731/go-prompt/internal/term/term.go:22:40: cannot use &saveTermios (type *syscall.Termios) as type *unix.Termios in argument to termios.Tcgetattr
ktr0731/go-prompt/internal/term/term.go:33:68: cannot use &o (type *syscall.Termios) as type *unix.Termios in argument to termios.Tcsetattr

## Screenshots

![Screenshot from 2020-10-23 11-38-00](https://user-images.githubusercontent.com/40004321/96973078-45dc3f00-1524-11eb-84ce-4d7483d34473.png)

## Environment
- OS: Dockerfile golang:1.15.3 image
- Evans version: latest
- `protoc` version: libprotoc 3.7.1

**Comment by ktr0731** [comment]
`go get` is not supported officially (see https://github.com/ktr0731/evans#not-recommended-go-get).
Please install Evans via another way.
