### ISSUE TITLE
Request: dump JSON file to be used by --file flag

### ISSUE THREAD

**Issue by Dariusch** [ktr0731/evans#323]
Hey guys, first of very nice tool!

I am missing a feature which might be quite handy.

Lets say we call a Service in the repl and we fill all the parameters needed.

The next time I start the repl those inputs are gone.

It would be nice to apply some kind of `--dump` flag to save the request in JSON Format which then can be used by the `--file` flag later on.

This would be a huge benefit for local development purposes.

**Comment by ktr0731** [comment]
Hi, @Dariusch. Thanks for your suggestion! As you said, we are sure that this feature will greatly improve the development cycle.
We are planning to provide a replay feature in the REPL mode in some form.

**Comment by ktr0731** [comment]
Hi, @Dariusch. We released a new version which contains a replay feature.
See https://github.com/ktr0731/evans#repeat-the-previous-call.
