### ISSUE TITLE
[FR] Support for gRPC Web

### ISSUE THREAD

**Issue by k2wanko** [ktr0731/evans#34]
I need gRPC Web support.

FYI: https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md

**Comment by ktr0731** [comment]
it's a good idea.
i'll consider gRPC web support!
thank you 😄

**Comment by ktr0731** [comment]
Finally, Evans acquired the ability to communicate to a gRPC Web enabled server at 0.6.0!
Please try it out.
