### ISSUE TITLE
Imports fail

### ISSUE THREAD

**Issue by troylelandshields** [ktr0731/evans#36]
I'd like to try `evans` out but I can't load any proto files that have imports. Is there some trick to tell it where to look for imported proto files?

```
evans x.proto
github.com/golang/protobuf/ptypes/timestamp/timestamp.proto: File not found.
x.proto: Import "github.com/golang/protobuf/ptypes/timestamp/timestamp.proto" was not found or had errors.
x.proto:11:3: "google.protobuf.Timestamp" is not defined.
```

And here's the proto file

```proto
syntax = "proto3";

package simpleproto;

import "github.com/golang/protobuf/ptypes/timestamp/timestamp.proto";

service PersonService {
    rpc SimpleRequest(Req) returns (Resp) {} 
}
message Req {
  google.protobuf.Timestamp Time = 1;
}

message Resp {
}
```

**Comment by ktr0731** [comment]
maybe you didn't add an import path for "github.com/golang/protobuf/ptypes/timestamp/timestamp.proto".  
Evans loads proto files same approach similar to protoc.
so, you need to add a `--proto` flag, for example, `github.com/golang/protobuf` is exist under `$GOPATH/src`, then just like:
``` bash
$ evans --proto $GOPATH/src x.proto
```

**Comment by ktr0731** [comment]
please re-open if you cannot use Evans.
