### ISSUE TITLE
Cannot omit an entire object in REPL

### ISSUE THREAD

**Issue by abstratt** [ktr0731/evans#387]
## Describe the bug

It does not seem possible to omit a field that is itself a message. The REPL ends up asking for the components of of the child message, which you can skip with ctrl-C, however, REPL issues an object for that field with default values, whereas it should be sending no object at all or an empty object.

## To reproduce

For a spec like this:

```
syntax = "proto3";
package mypackage;

import "google/protobuf/timestamp.proto";

service MyService {
   rpc myRpc(MyRequest) returns (MyResponse) {}
}

message MyRequest {
    string user_id = 1;
    MyFilters filters = 2;
}

message MyResponse {
  uint32 stats = 1;
}

message MyFilters {
    google.protobuf.Timestamp reference_time = 1;
    TimeWindow window = 2; 
}

message TimeWindow {
    uint32 amount = 1;
}

```

## Expected behavior

I should be able to issue a call to myRpc informing only the `user_id`. However, the REPL wants values for each component of `filters` (`reference_time` and `window`), which if have to omit one by one (ctrl-C), REPL will compute default values for them and issue a request like this:

```
{
  "user_id": "1111111111",
  "filters": {
    "reference_time": "1970-01-01T00:00:00Z",
    "window": {}
  }
}
```

when instead I should have given a chance to skip the filters field, and then the payload could have been something like this:

```
{
  "user_id": "1111111111",
  "filters": {}
}
```

or

```
{
  "user_id": "1111111111"
}
```

## Environment
- OS: Linux
- Terminal: 
- Evans version: 0.9.3
- `protoc` version: ?
- `protoc` plugin version (if you are using): ?

**Comment by ktr0731** [comment]
@abstratt 
Use `--dig-manually` option in REPL mode.

``` 
mypackage.MyService@127.0.0.1:50051> call -h
usage: call <method name>

Options:
      --bytes-from-file   interpret TYPE_BYTES input as a relative path to a file
      --dig-manually      prompt asks whether to dig down if it encountered to a message field
      --enrich            enrich response output includes header, message, trailer and status

mypackage.MyService@127.0.0.1:50051> call --dig-manually myRpc
user_id (TYPE_STRING) => foo
✔ skip
evans: map[grpc-client:[evans]]
evans: request:
{
  "userId": "foo"
}
```
