### ISSUE TITLE
Missing contributing guide

### ISSUE THREAD

**Issue by isopropylcyanide** [ktr0731/evans#413]
Hey there, thanks for the useful project.

As it stands today, there's no `CONTRIBUTING.md` guide for the project today. 
It'd be great if we could add it so it becomes easier to develop and contribute upstream.

**Comment by ktr0731** [comment]
Thanks for your feedback! It'd be a very useful resource for first-time contributors.
We'll add `CONTRIBUTING.md` in the near future.

**Comment by isopropylcyanide** [comment]
Thanks.
