### ISSUE TITLE
Feature request: Shift+Enter to skip the remaining fields when entering a message

### ISSUE THREAD

**Issue by danielyli** [ktr0731/evans#49]
Use case: When I’m calling a method that uses lots of fields, usually the first fields are the only ones I need to populate. Instead of pressing <kbd>Enter</kbd> <kbd>Enter</kbd> <kbd>Enter</kbd> <kbd>Enter</kbd> <kbd>Enter</kbd>, it’d be nice to just press  <kbd>Shift</kbd>+<kbd>Enter</kbd> once to complete the message.

**Comment by ktr0731** [comment]
it's a great feature! we need it.
thanks!

**Comment by ktr0731** [comment]
This feature is implemented in #180. Please try it out!
