### ISSUE TITLE
How to input a 2d array?

### ISSUE THREAD

**Issue by fans3210** [ktr0731/evans#495]
Sample is like below:

```
syntax = "proto3";

option go_package="./pb";

message Game {
    // each game contains 10 frames 
    repeated Frame frames = 1;
}

message Frame {
    // each throw should be an integer from 0 to 10
    // minimum 1 throw and maxmum 2 throws for frame 1-9 and maximum 3 throws for frame 10
   repeated uint32 throws = 1; 
}

```

But when I start typing, how to enter this 2d array. I tried to press Ctrl+D to escape but no luck. Thanks a lot!

**Comment by ktr0731** [comment]
Since Evans can't work properly in such a case, it's needed to specify `--add-repeated-manually` flag or `--dig-manually` flag explicitly.
Their flags let Evans asks whether input the field when a repeated field appears.
