### ISSUE TITLE
evans attempts to contact github.com port 443 during operation

### ISSUE THREAD

**Issue by QWERTY92009** [ktr0731/evans#507]
## Describe the bug

Twistlock reports that images containing evans are attempting to contact github during operation. 

`Outbound connection by /opt/bif/bin/evans to an unexpected port: 443 IP: 140.82.112.5`

In preprod and prod, this access will not be available. Can you describe the use case for this access, and whether preventing it will affect evans operation?

## Environment
- OS: 
- Terminal: 
- Evans version: 
- `protoc` version:
- `protoc` plugin version (if you are using):

**Comment by ktr0731** [comment]
Evans will automatically try to get a new version while the REPL is running.
Therefore, even if the communication is blocked, it will not have serious effects.

If you want to disable this feature, run Evans with `-e` option and edit `meta.autoupdate` to `true`.

**Comment by QWERTY92009** [comment]
Thanks @ktr0731!
