### ISSUE TITLE
After exiting evans REPL, the terminal doesn't echo anymore

### ISSUE THREAD

**Issue by xtofl** [ktr0731/evans#515]
## Describe the bug

After exiting evans REPL, the terminal doesn't echo anymore.

## To reproduce

```bash
/tmp/tmp.3pbHjjzpqb$ ls
evans  evans_linux_386.tar.gz  x.proto
/tmp/tmp.3pbHjjzpqb$ cat x.proto 
syntax = "proto3";
message X {
	int32 s = 1;
}
service Bar {
  rpc Foo(X) returns (X);
}
/tmp/tmp.3pbHjjzpqb$ evans repl --proto x.proto --host localhost --port 5000

  ______
 |  ____|
 | |__    __   __   __ _   _ __    ___
 |  __|   \ \ / /  / _. | | '_ \  / __|
 | |____   \ V /  | (_| | | | | | \__ \
 |______|   \_/    \__,_| |_| |_| |___/

 more expressive universal gRPC client


Bar@localhost:5000> exit
Good Bye :)
/tmp/tmp.3pbHjjzpqb$ evans  evans_linux_386.tar.gz  x.proto    <<<< I typed 'ls'
```

## Expected behavior

After exit, what I type is still echoed onto the terminal.

## Screenshots

![evans-no-echo](https://user-images.githubusercontent.com/441092/158331727-a654be9d-187c-4321-9ad9-7fd31e46afff.png)

## Environment
- OS: ubuntu 20.04
- Terminal: terminator, gnome-terminal
- Evans version: 0.10.3
- `protoc` version: n/a
- `protoc` plugin version (if you are using): n/a

**Comment by ktr0731** [comment]
Thanks for reporting the issue. This is fixed by https://github.com/ktr0731/evans/pull/528.
