### ISSUE TITLE
key mappings for inputting

### ISSUE THREAD

**Issue by ktr0731** [ktr0731/evans#52]
## Problem
Evans uses c-bata/go-prompt as the input method in REPL mode.
c-bata/go-prompt doesn't return <kbd>C-d</kbd> (io.EOF), only returns empty string.
so, Evans cannot determine whether empty input is <kbd>C-d</kbd> or just entered.
therefore, currently, Evans doesn't use <kbd>C-d</kbd> to notify end of input.  

## Currently key mappings
| mapping | result |
|:-|:-|
| <kbd>enter</kbd> | inputs default value (**in repeated fields, this mapping is disabled.**) |
| <kbd>enter</kbd> + <kbd>enter</kbd> | terminates inputting repeated fields |

## New key mappings for new features
I planning streaming modes.  
for these features, I will introduce new key mappings to terminate stream.

| mapping | result |
|:-|:-|
| <kbd>C-c</kbd> | terminates each streaming mode |

also to fix behavior of <kbd>enter</kbd> mapping in repeated fields, I considering abolish <kbd>enter</kbd> + <kbd>enter</kbd> mapping.  
instead of the mapping, <kbd>C-c</kbd> mapping terminates repeated fields inputting.

if you have any idea, please tell me.

thanks.

## Note
the final mapping table is:

| mapping | result |
|:-|:-|
| <kbd>enter</kbd> | inputs default value |
| <kbd>C-c</kbd> | terminates each mode (if current field is not repeated fields) |
| <kbd>C-c</kbd> | terminates inputting repeated fields |

if you want to terminate streaming mode in repeated fields inputting, you need to input <kbd>C-c</kbd> two times.

**Comment by mitramejia** [comment]
I had to go to the issues to now the keymap to end repeating inputs, it would be good to move this to README
