### ISSUE TITLE
0.10.5 REPL mode issue

### ISSUE THREAD

**Issue by a-watters** [ktr0731/evans#532]
Upon upgrading to the latest version via brew I'm seeing the below issue when trying to run -r mode, previously I was running 10.4 with no issues.

`evans: failed to run REPL mode: failed to instantiate a new spec: failed to instantiate the spec: failed to new protodesc: proto: could not resolve import "google/api/annotations.proto": not found

evans: failed to run REPL mode: failed to instantiate a new spec: failed to instantiate the spec: failed to list packages by gRPC reflection: failed to list services from reflection enabled gRPC server: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:50051: connect: connection refused"`

**Comment by ktr0731** [comment]
@a-watters 
I'm sorry for the inconvinience. We reverted changes in v0.10.5 and bump v0.10.6 🙇
