### ISSUE TITLE
How to connect to grpc services behind nginx reverse proxy with location address non-blank

### ISSUE THREAD

**Issue by LangInteger** [ktr0731/evans#547]
I can connect to my grpc service with `evans -r repl --port 20000 --host 127.0.0.1`. Case changes when I put grpc service behind nginx reversed proxy:

```shell
server {
    listen 80 http2;
    server_name  localhost;

    # Routing
    location /grpcgateway {
        grpc_pass grpc://grpcgateway_service;
    }
}

# Backend gRPC servers
#
upstream grpcgateway_service {
    zone routeguide_service 64k;
    server 127.0.0.1:20000;
}
```

How to connect to grpc service located at `127.0.0.1/grpcgateway`, `evans -r repl --port 20000 --host 127.0.0.1/grpcgateway` does not work

**Comment by ktr0731** [comment]
Evans (gRPC) dials to the server specified by using DNS, so it can't contain the path (`/grpcgateway`).
