### ISSUE TITLE
Cannot exit repeated fields

### ISSUE THREAD

**Issue by nonus25** [ktr0731/evans#574]
## Cannot exit repeated fields 
`<repeated> event::variant_set::value (TYPE_STRING)` `ctrl-D` or `ctrl-C` do not work 
structure is 
```
events
 variant_set     (field contain array of variant)
  variant           (field contain array of value)
   value
```
where value is string array 
so type event has field `variant_set` and this is array of variant and each variant has array of values

`https://stackoverflow.com/questions/73388597/evanscli-exit-repeated-fields-grpc`

**Comment by ktr0731** [comment]
Please follow to the issue template.

It can be avoided by specify `--dig-manually` option.

```
$ evans --proto api.proto repl
> call --dig-manually Unary 
```

**Comment by nonus25** [comment]
@ktr0731 thanks it works!
