### ISSUE TITLE
When starting Evans I get: panic: Malformed version: stable

### ISSUE THREAD

**Issue by sly07** [ktr0731/evans#575]
## Describe the bug
I've been using evans for a while now, just today noticed that when I start evans, it will startup for a couple of seconds and then crash with the following error:

panic: Malformed version: stable

goroutine 20 [running]:
github.com/hashicorp/go-version.Must(...)
        /Users/ktr/.ghq/pkg/mod/github.com/hashicorp/go-version@v1.4.0/version.go:102
github.com/ktr0731/go-updater/brew.(*HomebrewClient).LatestTag(0x14000400000, {0x104f1a9e8, 0x14000352800})
        /Users/ktr/.ghq/pkg/mod/github.com/ktr0731/go-updater@v0.1.5/brew/brew.go:66 +0x538
github.com/ktr0731/go-updater.(*Updater).Updatable(0x14000400030, {0x104f1a9e8, 0x14000352800})
        /Users/ktr/.ghq/pkg/mod/github.com/ktr0731/go-updater@v0.1.5/updater.go:48 +0x4c
github.com/ktr0731/evans/app.checkUpdate({0x104f1a9e8, 0x14000352800}, 0x14000350c90, 0x14000201720)
        /Users/ktr/.ghq/src/github.com/ktr0731/evans/app/update.go:64 +0x1d0
github.com/ktr0731/evans/app.runREPLCommand.func1()
        /Users/ktr/.ghq/src/github.com/ktr0731/evans/app/commands.go:269 +0x44
golang.org/x/sync/errgroup.(*Group).Go.func1(0x14000361230, 0x14000361260)
        /Users/ktr/.ghq/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go
        /Users/ktr/.ghq/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x60

## To reproduce
Begin evans version 0.10.8

## Expected behavior
no crash

## Environment
- OS: MacOS Monterey 12.5.1
- Terminal: zsh 5.8.1 (x86_64-apple-darwin21.0)
- Evans version: 0.10.8
- `protoc` version: libprotoc 3.15.7
- `protoc` plugin version (if you are using):

**Comment by akokubu** [comment]
I have same problem.I think this will solve the problem.
https://github.com/ktr0731/go-updater/pull/3

**Comment by guiguan** [comment]
for now, you can install the previous working version using: `go install github.com/ktr0731/evans@v0.10.7`

**Comment by TomohiroAkutsu** [comment]
I got around it by reverting back to 0.10.7.

1. Download source code( https://github.com/ktr0731/evans/releases/tag/v0.10.7 )
2. Run `make build` in downloaded directory
3. Run `brew uninstall evans`
4. Run `mv evans path-to-evans` (move step 2 artifacts)

**Comment by ktr0731** [comment]
Thanks for the report!
We just bumped v0.10.9 which fixes this issue. Please update by using Homebrew.

``` sh
brew upgrade evans
```
