### ISSUE TITLE
Using evans command line, how to display error_code and error_message from grpc api?

### ISSUE THREAD

**Issue by arfan** [ktr0731/evans#580]
Using evans command line, how to display error_code and error_message from grpc api?

**Comment by ktr0731** [comment]
Please specify `--enrich` flag to `call` sub-command.

``` sh
$ echo '<input>' | evans -r cli call --enrich <method>
```

There is a known issue with this feature, so please see also [this issue](https://github.com/ktr0731/evans/issues/545).
