### ISSUE TITLE
I can't connect with tls

### ISSUE THREAD

**Issue by sithu-go** [ktr0731/evans#589]
I can't connect with secure connection

ca.crt works in my client go code. but not in my terminal.

is something wrong with my command?

`evans -p 50051 -r --tls true --cacert ssl/ca.crt`
```
evans: failed to run REPL mode: failed to instantiate a new spec: failed to instantiate the spec: failed to list packages by gRPC reflection: failed to list services from reflection enabled gRPC server: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs"
```

**Comment by sithu-go** [comment]
Sorry I forget to add 

`--host localhost`

evans --host localhost -p 50051 -r --tls true --cacert ssl/ca.crt

**Comment by ktr0731** [comment]
Please follow the issue template.
Do you try to run with `--servername` option?

```
$ evans -r -t --cacert ssl/ca.crt --servername localhost
```
