### ISSUE TITLE
Repeated enum fails

### ISSUE THREAD

**Issue by danielyli** [ktr0731/evans#59]
```
message Request {
  User user = 1;
  repeated Attribute attributes = 2;
}

enum Attribute {
  ...
}
```

This causes Evans to do the following:

failed to input request message: Value for repeated field must be a slice; instead was int32

**Comment by ktr0731** [comment]
thanks for reporting a bug.
I'll check it after several hours ago 🙏

**Comment by ktr0731** [comment]
I fixed the bug!
