### ISSUE TITLE
brew install fails because my xcode command line tools are too new

### ISSUE THREAD

**Issue by Olof-IL** [ktr0731/evans#606]
## Describe the bug

I have XCode 14.1 installed, and the command line tools installed that comes with that version.

When trying to install evans with brew install I get this error message:

==> Installing evans from ktr0731/evans
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.4.

Is there a reason 14.1 command line tools does not work, or is the version check just wrong?

Version Output from  xcodebuild showing I indeed have developer tools installed
❯ xcodebuild -version
Xcode 14.1
Build version 14A400

## To reproduce
Install latest XCode
Try install evans with brew

## Expected behavior

Installation success

## Environment
- OS: MacOS 12.6 Monterey
- Evans version: v0.10.9

**Comment by ktr0731** [comment]
Evans doesn't depend on the Xcode Command Line Tools, Homebrew depends on it.
So I close this issue that doesn't relate to Evans. Could you find other resources to resolve it?
