### ISSUE TITLE
Skipping field not working with type `google/protobuf/struct.proto`

### ISSUE THREAD

**Issue by bobbylcraig** [ktr0731/evans#617]
## Describe the bug
As mentioned in your "skip the rest of the fields" section, some fields are skipped when they're passed over on the call. However, it seems as though the `google/protobuf/struct.proto` type isn't (I'm not sure if this is limited to this type, but it's the only one I can find that's impacted currently).

Thanks for all the work you put in here!

## To reproduce

With proto like...
```proto
syntax = "proto3";
package messages;
import "google/protobuf/struct.proto";

service ExampleService {
    rpc SendJson (SendJsonRequest) returns (SendJsonResponse) {}
}

message SendRequest {
    string UserID = 1;
    google.protobuf.Struct Details = 2;
    string OtherThing = 3;
}

message SendResponse {
    string UserID = 1;
    google.protobuf.Struct Details = 2;
    string OtherThing = 3;
}
```
If I run...
```bash
path.morepath.v1.MorePathHere@url:port>call SendJson

user_id (TYPE_STRING) => 123
<repeated> details::fields::key (TYPE_STRING) =>
other_thing (TYPE_STRING) => 
```
_Note: No values were entered for `details` or `other_thing`. Ctrl+D was entered._

I see a request on the server that looks like...
```json
{
    "user_id": "123",
    "details": {}
}
```
which correctly does _not_ include the `other_thing` but it _does_ include the `details` field (the problem).

## Expected behavior
With the above input in Evans, I'd expect a request on the server like
```json
{
    "user_id": "123"
}
```

## Environment
- OS: MacOS
- Terminal: MacOS Terminal v2.11
- Evans version: 0.10.9
Using `protoc-gen-twirp v8.1.0`

**Comment by ktr0731** [comment]
Sorry for being so late.

README  also says:

> By default, Evans digs down each message field automatically.

To avoid this behavior, please specify `--dig-manually`.
With this flag, Evans asks whether continue or skip when the next field is message type.

```
messages.ExampleService@127.0.0.1:50051> call --dig-manually SendJson
UserID (TYPE_STRING) => 123 
✔ skip
OtherThing (TYPE_STRING) =>
```

**Comment by ktr0731** [comment]
Feel free re-open this issue when you have some questions!

**Comment by michealroberts** [comment]
This doesn't work, it only seems to dig down or skip on the last field ... and when skip, the call is closed without a response or abort.
