### ISSUE TITLE
evans: command not found

### ISSUE THREAD

**Issue by JhonatanAlves4** [ktr0731/evans#618]
I try install evans with the  `go install github.com/ktr0731/evans@latest `

![Screenshot from 2022-12-23 10-57-50](https://user-images.githubusercontent.com/71884829/209347782-1b8a4c60-502a-42ae-988b-5c33cba0515a.png)

## Environment
- OS: Ubuntu
- `protoc` version: libprotoc 3.6.1

**Comment by ktr0731** [comment]
it seems like Evans is not installed correctly ($GOPATH is not included in $PATH?).
I close this issue due to it's not a problem related to Evans itself.
